// Code generated by go generate; DO NOT EDIT.
package aws

import (
	"context"

	"github.com/dop251/goja"
	"github.com/aws/aws-sdk-go-v2/service/kinesis"
)

type KinesisClient struct {
	*AWS
	sdk *kinesis.Client
}

func (a *AWS) newKinesisClient(call goja.ConstructorCall) *goja.Object {
	awsCfg := a.constructorCallToConfig("KinesisClient", call)

	sdk := kinesis.NewFromConfig(awsCfg)

	client := &KinesisClient{
		AWS: a,
		sdk: sdk,
	}

	return a.vu.Runtime().ToValue(client).ToObject(a.vu.Runtime())
}


func (c *KinesisClient) AddTagsToStream(obj *goja.Object,) goja.Value {
	in := &kinesis.AddTagsToStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.AddTagsToStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) CreateStream(obj *goja.Object,) goja.Value {
	in := &kinesis.CreateStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.CreateStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DecreaseStreamRetentionPeriod(obj *goja.Object,) goja.Value {
	in := &kinesis.DecreaseStreamRetentionPeriodInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DecreaseStreamRetentionPeriod(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DeleteResourcePolicy(obj *goja.Object,) goja.Value {
	in := &kinesis.DeleteResourcePolicyInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DeleteResourcePolicy(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DeleteStream(obj *goja.Object,) goja.Value {
	in := &kinesis.DeleteStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DeleteStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DeregisterStreamConsumer(obj *goja.Object,) goja.Value {
	in := &kinesis.DeregisterStreamConsumerInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DeregisterStreamConsumer(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DescribeLimits(obj *goja.Object,) goja.Value {
	in := &kinesis.DescribeLimitsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DescribeLimits(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DescribeStream(obj *goja.Object,) goja.Value {
	in := &kinesis.DescribeStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DescribeStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DescribeStreamConsumer(obj *goja.Object,) goja.Value {
	in := &kinesis.DescribeStreamConsumerInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DescribeStreamConsumer(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DescribeStreamSummary(obj *goja.Object,) goja.Value {
	in := &kinesis.DescribeStreamSummaryInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DescribeStreamSummary(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) DisableEnhancedMonitoring(obj *goja.Object,) goja.Value {
	in := &kinesis.DisableEnhancedMonitoringInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.DisableEnhancedMonitoring(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) EnableEnhancedMonitoring(obj *goja.Object,) goja.Value {
	in := &kinesis.EnableEnhancedMonitoringInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.EnableEnhancedMonitoring(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) GetRecords(obj *goja.Object,) goja.Value {
	in := &kinesis.GetRecordsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.GetRecords(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) GetResourcePolicy(obj *goja.Object,) goja.Value {
	in := &kinesis.GetResourcePolicyInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.GetResourcePolicy(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) GetShardIterator(obj *goja.Object,) goja.Value {
	in := &kinesis.GetShardIteratorInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.GetShardIterator(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) IncreaseStreamRetentionPeriod(obj *goja.Object,) goja.Value {
	in := &kinesis.IncreaseStreamRetentionPeriodInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.IncreaseStreamRetentionPeriod(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) ListShards(obj *goja.Object,) goja.Value {
	in := &kinesis.ListShardsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.ListShards(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) ListStreamConsumers(obj *goja.Object,) goja.Value {
	in := &kinesis.ListStreamConsumersInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.ListStreamConsumers(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) ListStreams(obj *goja.Object,) goja.Value {
	in := &kinesis.ListStreamsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.ListStreams(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) ListTagsForStream(obj *goja.Object,) goja.Value {
	in := &kinesis.ListTagsForStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.ListTagsForStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) MergeShards(obj *goja.Object,) goja.Value {
	in := &kinesis.MergeShardsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.MergeShards(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) PutRecord(obj *goja.Object,) goja.Value {
	in := &kinesis.PutRecordInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.PutRecord(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) PutRecords(obj *goja.Object,) goja.Value {
	in := &kinesis.PutRecordsInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.PutRecords(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) PutResourcePolicy(obj *goja.Object,) goja.Value {
	in := &kinesis.PutResourcePolicyInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.PutResourcePolicy(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) RegisterStreamConsumer(obj *goja.Object,) goja.Value {
	in := &kinesis.RegisterStreamConsumerInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.RegisterStreamConsumer(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) RemoveTagsFromStream(obj *goja.Object,) goja.Value {
	in := &kinesis.RemoveTagsFromStreamInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.RemoveTagsFromStream(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) SplitShard(obj *goja.Object,) goja.Value {
	in := &kinesis.SplitShardInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.SplitShard(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) StartStreamEncryption(obj *goja.Object,) goja.Value {
	in := &kinesis.StartStreamEncryptionInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.StartStreamEncryption(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) StopStreamEncryption(obj *goja.Object,) goja.Value {
	in := &kinesis.StopStreamEncryptionInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.StopStreamEncryption(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) SubscribeToShard(obj *goja.Object,) goja.Value {
	in := &kinesis.SubscribeToShardInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.SubscribeToShard(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) UpdateShardCount(obj *goja.Object,) goja.Value {
	in := &kinesis.UpdateShardCountInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.UpdateShardCount(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

func (c *KinesisClient) UpdateStreamMode(obj *goja.Object,) goja.Value {
	in := &kinesis.UpdateStreamModeInput{}
	if err := fromGojaObject(c.vu.Runtime(), obj, in); err != nil {
		panic(err)
	}

	out, err := c.sdk.UpdateStreamMode(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return c.vu.Runtime().ToValue(out)
}

