// Code generated by go generate; DO NOT EDIT.
package aws

import (
	"context"

	"github.com/dop251/goja"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)


func (a *AWS) ListBuckets(obj *goja.Object,) goja.Value {
	cfg, err := defaultConfig(context.TODO())
	if err != nil {
		panic(err)
	}

	in := &s3.ListBucketsInput{}
	if err := fromGojaObject(obj, in); err != nil {
		panic(err)
	}

	out, err := s3.NewFromConfig(cfg, func(o *s3.Options) {
        o.UsePathStyle = true  // Ensure path-style is used
    }).ListBuckets(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return a.vu.Runtime().ToValue(out)
}

func (a *AWS) ListObjects(obj *goja.Object,) goja.Value {
	cfg, err := defaultConfig(context.TODO())
	if err != nil {
		panic(err)
	}

	in := &s3.ListObjectsInput{}
	if err := fromGojaObject(obj, in); err != nil {
		panic(err)
	}

	out, err := s3.NewFromConfig(cfg, func(o *s3.Options) {
        o.UsePathStyle = true  // Ensure path-style is used
    }).ListObjects(context.Background(), in, )
    if err != nil {
		panic(err)
	}

	return a.vu.Runtime().ToValue(out)
}

