name: End-to-end test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Run Localstack & populate environment
        run: |
          cd examples
          docker compose up -d
          tofu init
          tofu apply -auto-approve

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build the extension
        run: |
          go install go.k6.io/xk6/cmd/xk6@master
          xk6 build \
            --output ./k6 \
            --with xk6-aws=.
      - name: Run k6 test
        run: |
          ./k6 run examples/s3.js
          ./k6 run examples/eventbridge.js
